apiVersion: v2
name: vertical-pod-autoscaler
description: Vertical Pod Autoscaler operator
type: application
version: 9.9.0
appVersion: "1.2.1"

dependencies:
- name: vertical-pod-autoscaler
  version: 9.9.0
  repository: https://cowboysysop.github.io/charts/
