{{- if .Values.apps.verticalPodAutoscaler.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
  - repoURL: https://cowboysysop.github.io/charts/
    chart: vertical-pod-autoscaler
    targetRevision: 9.9.0
    helm:
      valueFiles:
      - $values/vertical-pod-autoscaler/helm/vpa/values.yaml
  - repoURL: https://github.com/Costel03/k8s-homelab-gitops.git
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vpa-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
