# ClusterSecretStore for the "tls" KV v2 engine in Vault
# Vault engine: tls (version 2)
# Secrets: argocd, grafana, vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-tls
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.hashicorp-vault.svc:8200"
      path: "tls"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: eso
          key: token
---
# ClusterSecretStore for the "argocd" KV v2 engine in Vault
# Vault engine: argocd (version 2)
# Secrets: admin
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-argocd
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.hashicorp-vault.svc:8200"
      path: "argocd"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: eso
          key: token
