apiVersion: v2
name: metallb
description: Umbrella chart for MetalLB load balancer
type: application
version: 1.0.0
appVersion: "v0.15.3"

dependencies:
- name: metallb
  version: "0.15.3"
  repository: https://metallb.github.io/metallb
