nfs:
  server: 192.168.56.10
  path: /share

storageClass:
  name: nfs-client
  defaultClass: true
  reclaimPolicy: Retain
  archiveOnDelete: false

replicaCount: 1

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
