apiVersion: v2
name: zot
description: Umbrella chart for Zot OCI container registry
type: application
version: 1.0.0
appVersion: "2.1.2"

dependencies:
- name: zot
  version: "0.1.60"
  repository: https://zotregistry.dev/helm-charts
