apiVersion: v2
name: externalsecretoperator
version: 1.0.0
description: Umbrella chart for External Secrets Operator
appVersion: "v2.4.1"
type: application

dependencies:
- name: external-secrets
  version: "2.4.1"
  repository: https://charts.external-secrets.io
