apps:
  argocd:
    enabled: true
  containerRegistry:
    enabled: false
  externalSecretsOperator:
    enabled: false
  hashicorpVault:
    enabled: false
  metallb:
    enabled: true
  monitoring:
    enabled: true
  nfs:
    enabled: false
  nginxIngress:
    enabled: true
