apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecretoperator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.18
    helm:
      valueFiles:
      - $values/external-secrets-operator/helm/externalsecretoperator/values.yaml
  - repoURL: https://github.com/Costel03/k8s-homelab-gitops.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/Costel03/k8s-homelab-gitops.git
    targetRevision: main
    path: external-secrets-operator/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: eso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
